[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "consumer"
version = "0.1.0"
description = "A consumer package that depends on test-package"
requires-python = ">=3.6"
dependencies = [
    "test-package==0.1.0",
]
